"""empty message

Revision ID: fc7938a44b80
Revises: 261eed6be125
Create Date: 2020-01-18 11:55:18.728033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc7938a44b80'
down_revision = '261eed6be125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_project_id_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'Projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_project_id_fkey', 'books', 'Projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
